name: Frontend CI/CD to Cloud Run

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

jobs:
  build-deploy:
    name: Build & Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud CLI
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use Artifact Registry
        run: |
          gcloud auth configure-docker "us-central1-docker.pkg.dev" --quiet

      - name: Set environment variables
        run: |
          echo "IMAGE_NAME=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/frontend/frontend-image:latest" >> $GITHUB_ENV
          echo "SERVICE_NAME=frontend-service" >> $GITHUB_ENV

      - name: Build Docker image
        working-directory: ./frontend
        run: |
          docker build -t $IMAGE_NAME .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push $IMAGE_NAME

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE_NAME \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --project ${{ secrets.GCP_PROJECT_ID }}
