name: Frontend CI/CD to Cloud Run

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'gcloud'

      - name: Configure Docker for Artifact Registry
        run: |
          # The entire domain string should be in quotes to ensure it's passed as a single argument
          gcloud auth configure-docker "${{ secrets.GCP_REGION }}-docker.pkg.dev" --quiet

      - name: Build Docker Image for Frontend
        run: |
          # Ensure Dockerfile path and context are correct
          docker build -f ./frontend/Dockerfile -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/frontend/frontend:latest ./frontend

      - name: Push Docker Image to Artifact Registry
        run: |
          docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/frontend/frontend:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy frontend-service \
            --image=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/frontend/frontend:latest \
            --region=${{ secrets.GCP_REGION }} \
            --platform=managed \
            --allow-unauthenticated
